// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cubyzsaphreasoxbeglr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1Ynl6c2FwaHJlYXNveGJlZ2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NDk5MjAsImV4cCI6MjA1MjAyNTkyMH0.sKQURcDKfSuGUyOkPlFNaFlqfIlXvlnCGsb-qf2sa1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);